id: cappuccino
name: cappuccino

vibversion: 1.0.0
includespath: includes.container

stages:
  - id: build
    args:
      DEBIAN_FRONTEND: noninteractive
    base: ghcr.io/vanilla-os/desktop:main

    addincludes: true
    singlelayer: false

    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    modules:
      - type: shell
        name: system
        commands:
          - lpkg --unlock
          - apt-get update
          - apt-get upgrade -y

      - type: apt
        name: dependencies
        sources:
          - path: apt.inst

      # dx
      # dx

      - type: cargo
        name: cargo
        sources:
          - atuin
          - bandwhich
          - bat
          - delta
          - dust
          - eza
          - fd
          - procs
          - sd
          - starship
          - tealdeer
          - television
          - tokei
          - viddy

      - type: go
        name: direnv
        source:
          url: https://github.com/direnv/direnv.git
          type: git
          branch: master

      - type: go
        name: glow
        source:
          url: https://github.com/charmbracelet/glow.git
          type: git
          branch: master

      - type: go
        name: lazydocker
        source:
          url: https://github.com/jesseduffield/lazydocker.git
          type: git
          branch: master

      - type: go
        name: lazygit
        source:
          url: https://github.com/jesseduffield/lazygit.git
          type: git
          branch: master

      - type: shell
        name: zed-editor
        commands:
          - mkdir -p /opt/zed
          - curl -L "https://zed.dev/api/releases/stable/latest/zed-linux-x86_64.tar.gz" -o /tmp/zed.tar.gz
          - tar -xvf /tmp/zed.tar.gz -C /opt/zed
          - ln -sf /opt/zed/zed.app/bin/zed /usr/local/bin/zed
          - mkdir -p /usr/share/applications
          - cp /opt/zed/zed.app/share/applications/zed.desktop /usr/share/applications/dev.zed.Zed.desktop
          - sed -i "s|Icon=zed|Icon=/opt/zed/zed.app/share/icons/hicolor/512x512/apps/zed.png|g" /usr/share/applications/dev.zed.Zed.desktop
          - sed -i "s|Exec=zed|Exec=/usr/local/bin/zed|g" /usr/share/applications/dev.zed.Zed.desktop

      # ux
      # ux

      - type: shell
        name: fix-xcompose
        commands:
          - chmod 644 /etc/XCompose
          - flatpak override --system --env=QT_IM_MODULE=xim
          - flatpak override --system --env=GTK_IM_MODULE=xim
          - flatpak override --system --env=XMODIFIERS=@im=none
          - flatpak override --system --filesystem=/etc/.XCompose

      - type: flatpak
        name: flathub
        user:
          install:
            - be.alexandervanhee.gradia
            - com.brave.Browser
            - com.github.IsmaelMartinez.teams_for_linux
            - com.github.rafostar.Clapper
            - com.github.wwmm.easyeffects
            - com.google.Chrome
            - com.obsproject.Studio
            - com.spotify.Client
            - de.haeckerfelix.Fragments
            - dev.vencord.Vesktop
            - io.github.tobagin.karere
            - io.gitlab.adhami3310.Impression
            - io.gitlab.librewolf-community
            - io.missioncenter.MissionCenter
            - org.filezillaproject.Filezilla
            - org.mozilla.firefox
            - org.onlyoffice.desktopeditors
            - org.prismlauncher.PrismLauncher
            - org.telegram.desktop
            - page.tesk.Refine
            - io.github.flattool.Ignition

          repourl: https://flathub.org/repo/flathub.flatpakrepo
          reponame: flathub

      # proprietary
      # proprietary

      - type: shell
        name: 1password
        commands:
          - mkdir -p /etc/debsig/policies/AC2D62742012EA22/
          - mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
          - curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
          - echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | tee /etc/apt/sources.list.d/1password.list
          - curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
          - curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
          - apt update && apt install -y 1password 1password-cli
          - chmod +x /usr/bin/vos-opt-symlink
          - systemctl enable vos-opt-symlink.service

      - type: shell
        name: tailscale
        commands:
          - curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg | tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
          - curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list | tee /etc/apt/sources.list.d/tailscale.list
          - apt-get update && apt-get install -y tailscale
          - systemctl enable tailscaled

      - type: shell
        name: warp-cli
        commands:
          - curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          - echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ bookworm main" | tee /etc/apt/sources.list.d/cloudflare-client.list
          - apt-get update && apt-get install -y cloudflare-warp

      # finalize
      # finalize

      - type: shell
        name: set-image-abroot-config
        commands:
          - IMAGE_NAME="$(cat /image-info/image-name)"
          - echo custom image name "$IMAGE_NAME"
          - IMAGE_NAME_ESCAPED="$(echo $IMAGE_NAME | sed 's/\//\\\//g')"
          - sed -i "s/changed_automatically_by_vib/$IMAGE_NAME_ESCAPED/g" /usr/share/abroot/abroot.json
          - rm -rf /image-info

      - type: shell
        name: cleanup-pre
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock

      - type: fsguard
        name: fsguard

        GenerateKey: true
        CustomFsGuard: false

        FilelistPaths: ["/usr/bin"]
        FsGuardLocation: "/usr/sbin/FsGuard"

        modules:
          - type: shell
            name: setup
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - type: shell
        name: cleanup-post
        commands:
          - rm -rf /tmp/*
          - rm -rf /sources
          - rm -rf /var/tmp/*
