id: cappuccino
name: cappuccino

vibversion: 1.0.0
includespath: includes

stages:
  - id: build
    args:
      DEBIAN_FRONTEND: noninteractive
    base: ghcr.io/vanilla-os/desktop:main

    addincludes: true
    singlelayer: false

    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    modules:
      - type: shell
        name: system
        commands:
          - lpkg --unlock
          - apt-get update
          - apt-get upgrade -y

      - type: apt
        name: vanilla
        sources:
          - path: vanilla.inst

      - type: includes
        name: modules
        includes:
          - build/atuin.yml
          - build/bandwhich.yml
          - build/bat.yml
          - build/delta.yml
          - build/direnv.yml
          - build/dust.yml
          - build/eza.yml
          - build/fd.yml
          - build/glow.yml
          - build/just.yml
          - build/lazydocker.yml
          - build/lazygit.yml
          - build/procs.yml
          - build/sd.yml
          - build/starship.yml
          - build/tealdeer.yml
          - build/television.yml
          - build/tokei.yml
          - build/viddy.yml
          - prebuilt/1password.yml
          - prebuilt/docker.yml
          - prebuilt/flathub.yml
          - prebuilt/tailscale.yml
          - prebuilt/zed-editor.yml
          - fix-flatpak-xcompose.yml
          - set-image-abroot-config.yml

      - type: shell
        name: cleanup-a
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock

      - type: fsguard
        name: fsguard

        GenerateKey: true
        CustomFsGuard: false

        FilelistPaths: ["/usr/bin"]
        FsGuardLocation: "/usr/sbin/FsGuard"

        modules:
          - type: shell
            name: setup
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - type: shell
        name: cleanup-b
        commands:
          - rm -rf /tmp/*
          - rm -rf /sources
          - rm -rf /var/tmp/*
